// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxsczMRnR0F2J1KsYWIQ0S9Y8GuCnEMhY',
    appId: '1:893702182018:web:727336a7ff895a43dd509b',
    messagingSenderId: '893702182018',
    projectId: 'namazbajamat',
    authDomain: 'namazbajamat.firebaseapp.com',
    storageBucket: 'namazbajamat.appspot.com',
    measurementId: 'G-WKHFYMBPPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8iGgX2XtNY80XyDwA6lu6a72i7K70ck',
    appId: '1:893702182018:android:384becaac08bd973dd509b',
    messagingSenderId: '893702182018',
    projectId: 'namazbajamat',
    storageBucket: 'namazbajamat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_NRjzEimO6Kh_s7PejVJDK3fCP5F-XRU',
    appId: '1:893702182018:ios:b9f04acdfb223d2ddd509b',
    messagingSenderId: '893702182018',
    projectId: 'namazbajamat',
    storageBucket: 'namazbajamat.appspot.com',
    iosBundleId: 'com.example.namazBaJamat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_NRjzEimO6Kh_s7PejVJDK3fCP5F-XRU',
    appId: '1:893702182018:ios:b9f04acdfb223d2ddd509b',
    messagingSenderId: '893702182018',
    projectId: 'namazbajamat',
    storageBucket: 'namazbajamat.appspot.com',
    iosBundleId: 'com.example.namazBaJamat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxsczMRnR0F2J1KsYWIQ0S9Y8GuCnEMhY',
    appId: '1:893702182018:web:04a42713fd465416dd509b',
    messagingSenderId: '893702182018',
    projectId: 'namazbajamat',
    authDomain: 'namazbajamat.firebaseapp.com',
    storageBucket: 'namazbajamat.appspot.com',
    measurementId: 'G-F9H5VF8BXE',
  );
}
